### PR TITLE
Pr attitude rate setpoint topic

### PR DESCRIPTION
**Pull request by chamdanedu**
Adds attitude rate setpoint topic and changes velocity loop to listen to this topic instead of the manual topic.

### CODE REVIEW

**Comment by bperseghetti** [comment]
Hi @chamdanedu I believe that if you do a `west format` when in cerebri directory it should fix the format error.

**Comment by chamdanedu** [comment]
@JoeyForster Can you commit with -s added to sign off so we can pass the DCO

**Comment by bperseghetti** [comment]
https://github.com/CogniPilot/cerebri/actions/runs/8178633009/job/22362981967?pr=132

Linting (`west format`)

Also maybe do a git rebase and cleanup the commits slightly and sign them with key so DCO passes.

**Comment by chamdanedu** [comment]
I did the rebase, but it seemed to just have merged with this repository rather than rebasing it. How would I actually rebase this request.

**Comment by bperseghetti** [comment]
image
You can probably for now just squash them all and do a reword and make sure to sign the commit (worst case you can sign it with `git commit --amend -s` after squashing it. Or slightly more complicated you can reword multiple and selectively squash.

**Comment by bperseghetti** [comment]
Notice how I switched them from pick to s and r respectively.

**Comment by chamdanedu** [comment]
Alright I believe that should work. Thank you for all the help!

**Comment by jgoppert** [comment]
I'm going to go ahead and merge this into the pr-attitude branch to sync our development. Before we merge into main, we should do a more thorough review of flight performance after manual tuning.

**Pull request merged**
